SET FOREIGN_KEY_CHECKS = 0;

USE mydb;

TRUNCATE TABLE Vestiging;
TRUNCATE TABLE Bedrijf;
TRUNCATE TABLE klant;
TRUNCATE TABLE Adres;
TRUNCATE TABLE Huur;
TRUNCATE TABLE Fiets;
TRUNCATE TABLE Contract